export enum ChatErrorMessage {
    ILLEGAL_CHARACTER = 'ILLEGAL_CHARACTER',
    TOO_MANY_CHARACTERS = 'TOO_MANY_CHARACTERS',
    INSUFFICIENT_RIGHTS = 'INSUFFICIENT_RIGHTS',
    INVALID_DATE = 'INVALID_DATE',
    INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
}