export enum Command {
    HELP = 'help',
    START = 'start',
    STOP = 'stop',
    CANCEL = 'cancel',
    NEW_CUP = 'newcup',
    DELETE_CUP = 'delcup',
    JOIN_CUP = 'joincup',
    GET_JOINED_CUPS = 'mycups',
    GET_ALL_CUPS = 'getcups',
    GET_ALL_GAMES = 'getgames',
    GET_MY_GAMES = 'mygames',
    GET_MY_ELO = 'elo',
    NEW_GAME = 'newgame',
    METADATA = 'metadata',
    CHEERS = 'cheers',
    PROST = 'prost',
    GIB = 'gib',
    PROXY = 'proxy',
}