export enum ChatErrorMessage {
    ILLEGAL_CHARACTER = 'ILLEGAL_CHARACTER',
    TOO_MANY_CHARACTERS = 'TOO_MANY_CHARACTERS',
    NO_CUPS = 'NO_CUPS',
    NO_ACTIVE_CUPS = 'NO_ACTIVE_CUPS',
    NO_JOINED_CUPS = 'NO_JOINED_CUPS',
    INSUFFICIENT_RIGHTS = 'INSUFFICIENT_RIGHTS',
    DUPLICATE_NAME = 'DUPLICATE_NAME',
    INVALID_DATE = 'INVALID_DATE',
    INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
    CACHE_EMPTY = 'CACHE_EMPTY',
    CACHE_INVALID_FORMAT = 'CACHE_INVALID_FORMAT',
    UNAVAILABLE_PLAYER = 'UNAVAILABLE_PLAYER',
}